# Base Setup
font_family = NotoSans Nerd Font
monospace_font = NotoSans Nerd Font
icon_theme = Adwaita

# Font Sizes
font_size_h1 = 16
font_size_h2 = 14
font_size_h3 = 12
font_size_regular = 10
font_size_small = 8

# Catppuccin Mocha
background = 0xFA11111B
base = 0xFF1E1E2E
text = 0xFFCDD6F4
alternate_base = 0xFF181825
bright_text = 0xFFF5E0DC
accent = 0xFFCBA6F7
accent_secondary = 0xFFCBA6F7

