general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 30
    on-timeout = ~/.config/hypr/scripts/hypridle.sh --state-idle
    on-resume = ~/.config/hypr/scripts/hypridle.sh --state-restore
}

# listener { 
#     timeout = 30
#     on-timeout = brightnessctl -sd rgb:kbd_backlight set 0
#     on-resume = brightnessctl -rd rgb:kbd_backlight
# }

listener {
    timeout = 60
    on-timeout = loginctl lock-session
}

listener {
    timeout = 90
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on && brightnessctl -r # ~/.config/hypr/scripts/hypridle.sh --state-restore
}

listener {
    timeout = 300
    on-timeout = systemctl suspend
}
