# See https://wiki.hypr.land/Configuring/Permissions/
permission = /usr/(bin|local/bin)/grim, screencopy, allow
permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
# permission = /usr/(bin|local/bin)/hyprpm, plugin, allow

# See https://wiki.hypr.land/Configuring/Keywords/
$terminal = kitty
$fileManager = nautilus
$menu = rofi -show drun -theme ~/.config/rofi/theme.rasi

# See https://wiki.hypr.land/Configuring/Environment-variables/
env = XCURSOR_THEME, Bibata-Modern-Ice
env = XCURSOR_SIZE, 24
env = HYPRSHOT_DIR, $HOME/Pictures/Screenshots
env = DOTNET_ROOT, /usr/bin/dotnet
env = PATH, $PATH:/usr/bin/dotnet:/usr/bin/dotnet/tools

misc:disable_splash_rendering = 1

source = ./modules/autostart.conf

source = ./modules/monitors.conf
source = ./modules/decorations.conf
source = ./modules/devices.conf
source = ./modules/bindings.conf

source = ./modules/rules.conf

source = ./modules/ecosystem.conf

# HyprMod managed settings
source = /home/snippets/.config/hypr/hyprmod.conf
