# See https://wiki.hypr.land/Configuring/Variables/#general
general:gaps_in = 5
general:gaps_out = 10

general:border_size = 1
general:resize_on_border = 1

general:col.active_border = $active_border
general:col.inactive_border = $inactive_border
general:allow_tearing = false

general:layout = dwindle
dwindle:smart_split = 0

# See https://wiki.hypr.land/Configuring/Variables/#decoration
decoration:rounding = 12
decoration:rounding_power = 2.0

decoration:active_opacity = 0.8
decoration:inactive_opacity = 0.8

decoration:shadow:enabled = 0

# decoration:blur:enabled = true
# decoration:blur:contrast = 0.9
# decoration:blur:noise = 0.015
# decoration:blur:passes = 2
# decoration:blur:size = 6
# decoration:blur:brightness = 0.8
# decoration:blur:vibrancy = 0.15
# decoration:blur:new_optimizations = true

# Frosted Glass Effect
decoration:blur:enabled = true
decoration:blur:size = 12            # The "radius" of the blur
decoration:blur:passes = 4           # How many times the blur is processed (higher = smoother)

decoration:blur:vibrancy = 0.1696    # Boosts colors for a more vivid glass look
decoration:blur:noise = 0.0117       # Adds a tiny bit of grain to mimic real glass texture
decoration:blur:contrast = 0.8916    # Keeps the text readable against the background
decoration:blur:brightness = 0.8172  # Adjusts the "opacity" feel of the light
        
decoration:blur:new_optimizations = true
decoration:blur:xray = true          # Allows the blur to see through other floating windows

decoration:dim_strength = 0.15

# See https://wiki.hypr.land/Configuring/Dwindle-Layout/ for more
dwindle {
    pseudotile = true # Master switch for pseudotiling. Enabling is bound to mainMod + P in the keybinds section below
    preserve_split = true # You probably want this
}

# See https://wiki.hypr.land/Configuring/Master-Layout/ for more
master {
    new_status = master
}
