# See https://wiki.hypr.land/Configuring/Variables/#input
input:kb_layout = us
input:kb_variant =
input:kb_model =
input:kb_options =
input:kb_rules =
input:follow_mouse = 1
input:sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
input:touchpad:natural_scroll = false

# See https://wiki.hypr.land/Configuring/Gestures
# Format: gesture = fingers, direction, action, [options]
# gesture = 3, horizontal, workspace

# 3-finger horizontal swipe for workspaces
# 'scale' replaces 'workspace_swipe_distance' (higher = more distance needed)
# 'cancel_ratio' is the percentage of swipe before it commits (0.25 = 25%)
gesture = 3, horizontal, workspace
gesture = 3, pinchin, fullscreen

cursor:hide_on_tablet = 1
cursor:inactive_timeout = 0
cursor:no_hardware_cursors = true
input:follow_mouse = 2
input:sensitivity = 0.25
input:touchpad:natural_scroll = 1
