## Other rules
## Workspace Rules: https://wiki.hypr.land/Configuring/Workspace-Rules/

# https://wiki.hypr.land/Configuring/Variables/#misc
misc {
    force_default_wallpaper = 0 # Set to 0 or 1 to disable the anime mascot wallpapers
    disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background. :(
}

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

# Nautilus file manager
windowrule {
    name = open-nautilus-floating
    match:class = ^(org.gnome.Nautilus)$
    float = yes
    size = 920 600
    center = true
    max_size = 1000 800
}

# Rules for Nautilus-only file dialogs
windowrule {
    name = open-nautilus-popup-floating
    # Match criteria (props)
    match:class = ^(org.gnome.Nautilus)$
    match:title = ^(Open|Select|Choose|Save|Library)(.*)$
    
    # Effects
    float = on
    size = 720 640
    center = on
    max_size = 1000 800
}

# Rule for the GNOME portal (file picker used by other apps)
windowrule {
    name = open-gnome-popup-floating
    match:class = ^(xdg-desktop-portal-gnome)$
    float = on
    size = 720 640
    center = on
}

# Rule for the GTK portal (file picker used by other apps)
windowrule {
    name = open-gnome-popup-floating
    match:class = ^(xdg-desktop-portal-gtk)$
    float = on
    size = 720 640
    center = on
}

# Rule for Antigravity popup
windowrule {
    name = open-antigravity-popup-floating
    # Replace with the exact class found from hyprctl
    match:class = ^(antigravity)$
    match:title = ^(Background Agents|Agents Manager|Launchpad)(.*)$
    
    float = on
    # Using 'initial' or removing fixed sizes allows the app to define its box
    
    border_size = 0
    no_shadow = on
    no_blur = on

    center = on
}