# Colors
#$active_border = rgba(33CCFFEE) rgba(00FF99EE) 45deg
# $active_border = rgba(81C8BEFF) rgba(E5C890FF) 45deg
$active_border = rgba(C6D0F5A0)

#inactive_border = rgba(595959AA)
# $inactive_border = rgba(C6D0F5AA)
$inactive_border = rgba(C6D0F525)

