#Environment variables
env = ZDOTDIR,/home/cachyos/.config/zsh
env = XCURSOR_THEME,Bibata-Modern-Ice
env = XCURSOR_SIZE,24
env = EDITOR,micro
env = DOTNET_ROOT,/usr/bin/dotnet
# env = PATH, $PATH:/usr/bin/dotnet:/usr/bin/dotnet/tools
env = GTK_CSD,0

source = ./modules/appearance.conf
source = ./modules/animations.conf
source = ./modules/peripherals.conf
source = ./modules/rulesets.conf
source = ./modules/keybinds.conf

source = ./layouts/config.conf
source = ./layouts/dwindle.conf
source = ./layouts/master.conf
source = ./layouts/overview.conf
source = ./layouts/scroller.conf

exec-once = /usr/lib/xdg-desktop-portal-wlr
exec-once = swaybg -i $HOME/Pictures/Wallpapers/robot-wallpaper-3840x2160-abandoned-wilderness-26619.jpg -m fill
exec-once = elephant
exec-once = walker --gapplication-service
