#Environment variables
env = ZDOTDIR,/home/snippets/.config/zsh
env = XCURSOR_THEME,XCursor-Bibata-Modern-Ice
env = XCURSOR_SIZE,24
env = EDITOR,micro

source = ./.appearance.conf
source = ./.animations.conf
source = ./.layouts.conf
source = ./.peripherals.conf
source = ./.rulesets.conf
source = ./.bindings.conf

exec-once = swaybg -i $HOME/.config/wallpapers/robot-wallpaper-3840x2160-abandoned-wilderness-26619.jpg -m fill
