#Environment variables
env = ZDOTDIR,/home/vnsnippets/.config/zsh
env = XCURSOR_THEME,XCursor-Bibata-Modern-Ice
env = XCURSOR_SIZE,24
env = EDITOR,micro

env = HYPRSHOT_DIR,/home/vnsnippets/Pictures/Screenshots

source = ./modules/appearance.conf
source = ./modules/animations.conf
source = ./modules/peripherals.conf
source = ./modules/rulesets.conf
source = ./modules/keybinds.conf

source = ./layouts/config.conf
source = ./layouts/dwindle.conf
source = ./layouts/master.conf
source = ./layouts/overview.conf
source = ./layouts/scroller.conf

exec-once = swaybg -i $HOME/.config/wallpapers/robot-wallpaper-3840x2160-abandoned-wilderness-26619.jpg -m fill
exec-once = quickshell -p /home/vnsnippets/.config/quickshell/Shell.qml
