bind = SUPER+Shift, R, reload_config

# Applications
bind = SUPER, Return, spawn, foot
bind = SUPER, E, spawn, nautilus
bind = SUPER, Escape, killclient
bind = SUPER, TAB, spawn_shell, quickshell -p ~/.config/quickshell/Shell.qml ipc call console toggle

# Old bindings for apps that will be removed
bind = ALT, Return, spawn, kitty
bind = SUPER+ALT, Tab, spawn, walker

# Layouts
bind = SUPER, Grave, switch_layout

# Window Swap
bind = SUPER+SHIFT, Up, exchange_client, up
bind = SUPER+SHIFT, Down, exchange_client, down
bind = SUPER+SHIFT, Left, exchange_client, left
bind = SUPER+SHIFT, Right, exchange_client, right

# Window Move
mousebind = SUPER, BTN_LEFT, moveresize, curmove
mousebind = SUPER, BTN_RIGHT, moveresize, curresize

# Window Float
bind = ALT, Tab, togglefloating

# Tags (Workspaces)
bind = SUPER, 1, view, 1, 0
bind = SUPER, 2, view, 2, 0
bind = SUPER, 3, view, 3, 0
bind = SUPER, 4, view, 4, 0
bind = SUPER, 5, view, 5, 0
bind = SUPER, 6, view, 6, 0
bind = SUPER, 7, view, 7, 0
bind = SUPER, 8, view, 8, 0
bind = SUPER, 9, view, 9, 0

# Window Move to Tag
bind = SUPER, Left, tagtoleft, 1
bind = SUPER, Right, tagtoright, 1

# Audio and Microphone control
bind = NONE, XF86AudioRaiseVolume, spawn, wpctl set-volume -l 1 @DEFAULT_SINK@ 5%+
bind = NONE, XF86AudioLowerVolume, spawn, wpctl set-volume @DEFAULT_SINK@ 5%-
bind = NONE, XF86AudioMute, spawn, wpctl set-mute @DEFAULT_SINK@ toggle
bind = NONE, XF86AudioMicMute, spawn, wpctl set-mute @DEFAULT_SOURCE@ toggle

# Volume control via Player CTL
bind = NONE, XF86AudioNext, spawn, playerctl next
bind = NONE, XF86AudioPause, spawn, playerctl play-pause
bind = NONE, XF86AudioPlay, spawn, playerctl play-pause
bind = NONE, XF86AudioPrev, spawn, playerctl previous

# Brightness control via Brightness CTL
bind = NONE, XF86MonBrightnessUp, spawn, brightnessctl set 5%+
bind = NONE, XF86MonBrightnessDown, spawn, brightnessctl set 5%-

# Hyprland Leftovers
# bind  =  SUPER, L, spawn, pidof hyprlock || hyprlock
bind = SUPER, Delete, quit

# Screenshot
bind = NONE, Print, spawn_shell, $HOME/.config/mango/scripts/satty.sh --full --save
bind = SUPER+SHIFT, S, spawn_shell, $HOME/.config/mango/scripts/satty.sh --region
bind = SUPER, Print , spawn_shell, $HOME/.config/mango/scripts/satty.sh --region --save

