# Supported Layouts:
# - tile
# - scroller
# - grid
# - deck
# - monocle
# - center_tile
# - vertical_tile
# - vertical_scroller

tagrule=id:1,layout_name:center_tile
tagrule=id:2,layout_name:center_tile
tagrule=id:3,layout_name:center_tile
tagrule=id:4,layout_name:center_tile
tagrule=id:5,layout_name:center_tile
tagrule=id:6,layout_name:center_tile
tagrule=id:7,layout_name:center_tile
tagrule=id:8,layout_name:center_tile
tagrule=id:9,layout_name:center_tile

# layer rule
layerrule=animation_type_open:zoom,layer_name:rofi
layerrule=animation_type_close:zoom,layer_name:rofi

# Window: Nautilus
windowrule=isfloating:1,width:960,height:600,animation_type_open:zoom,animation_type_close:zoom,appid:Nautilus
windowrule=width:960,height:600,animation_type_open:zoom,animation_type_close:zoom,appid:xdg-desktop-portal-gtk
windowrule=focused_opacity:1.0,unfocused_opacity:1.0,appid:firefox

# Force Telegram to
# - Open specifically on laptop screen
# - Float so it ignores tiling layouts
# - Use custom dimensions as fractions (0.25 = 25% width and height)
windowrule=telegram-desktop,eDP-1
windowrule=telegram-desktop,isfloating:1
windowrule=telegram-desktop,width_fraction:0.25
