# Supported Layouts:
# - tile
# - scroller
# - grid
# - deck
# - monocle
# - center_tile
# - vertical_tile
# - vertical_scroller

tagrule=id:1,layout_name:center_tile
tagrule=id:2,layout_name:scroller
tagrule=id:3,layout_name:scroller
tagrule=id:4,layout_name:scroller
tagrule=id:5,layout_name:scroller
tagrule=id:6,layout_name:scroller
tagrule=id:7,layout_name:scroller
tagrule=id:8,layout_name:scroller
tagrule=id:9,layout_name:scroller

# MPV: Float
windowrule=appid:mpv,isfloating:1,width:960,height:720,animation_type_open:zoom,animation_type_close:zoom

# Nautilus: Float
windowrule=appid:Nautilus,isfloating:1,width:960,height:720,animation_type_open:zoom,animation_type_close:zoom
windowrule=appid:xdg-desktop-portal-gtk,width:960,height:600,animation_type_open:zoom,animation_type_close:zoom

# Telegram
# - Open specifically on laptop screen
# - Float so it ignores tiling layouts
# - Use custom dimensions as fractions (0.25 = 25% width and height)
# windowrule=telegram-desktop,eDP-1
# windowrule=telegram-desktop,isfloating:1
# windowrule=telegram-desktop,width_fraction:0.25

# Pavucontrol: Float
windowrule=appid:pavucontrol,isfloating:1,width:960,height:600,animation_type_open:zoom,animation_type_close:zoom

# NWG Look: Float
windowrule=appid:nwg-look,isfloating:1,width:960,height:600,animation_type_open:zoom,animation_type_close:zoom

# Satty, Grim, Slurp
windowrule=appid:com.gabm.satty,noswallow:1,isfullscreen:0,isfloating:1,animation_type_open:zoom,animation_type_close:zoom

# Firefox
windowrule=title:Picture-in-Picture,appid:firefox,width:480,height:270,noswallow:1,isfullscreen:0,isfloating:1,offsetx:-98,offsety:-97,animation_type_open:zoom,animation_type_close:zoom
