# Supported Layouts:
# - tile
# - scroller
# - grid
# - deck
# - monocle
# - center_tile
# - vertical_tile
# - vertical_scroller

tagrule=id:1,layout_name:scroller
tagrule=id:2,layout_name:scroller
tagrule=id:3,layout_name:scroller
tagrule=id:4,layout_name:scroller
tagrule=id:5,layout_name:scroller
tagrule=id:6,layout_name:scroller
tagrule=id:7,layout_name:scroller
tagrule=id:8,layout_name:scroller
tagrule=id:9,layout_name:scroller

# layer rule
# layerrule=animation_type_open:zoom,layer_name:rofi
# layerrule=animation_type_close:zoom,layer_name:rofi
layerrule=layer_name:walker,animation_type_open:zoom,animation_type_close:zoom

# Nautilus: Float
windowrule=appid:Nautilus,isfloating:1,width:960,height:720,animation_type_open:zoom,animation_type_close:zoom
windowrule=appid:xdg-desktop-portal-gtk,width:960,height:600,animation_type_open:zoom,animation_type_close:zoom

# Telegram
# - Open specifically on laptop screen
# - Float so it ignores tiling layouts
# - Use custom dimensions as fractions (0.25 = 25% width and height)
# windowrule=telegram-desktop,eDP-1
# windowrule=telegram-desktop,isfloating:1
# windowrule=telegram-desktop,width_fraction:0.25

# Pavucontrol: Float
windowrule=appid:pavucontrol,isfloating:1,width:960,height:600,animation_type_open:zoom,animation_type_close:zoom

# Flameshot
# windowrule=noswallow:1,appid:flameshot
# windowrule=isfullscreen:1,appid:flameshot
# windowrule=animation_type_open:none,appid:flameshot
# windowrule=animation_type_close:none,appid:flameshot

# Satty, Grim, Slurp
windowrule=appid:com.gabm.satty,noswallow:1,isfullscreen:0,isfloating:1,animation_type_open:zoom,animation_type_close:zoom

# hl.window_rule({
#     name  = "float-satty",
#     match = { class = "com.gabm.satty" },
#     float = true,
#     max_size = "1600 1000",
#     animation = "popin 25%"
# })