# Used by: tile, vertical_tile, center_tile, right_tile

# New windows become master window
new_is_master=1

# Allocated space for master window
default_mfact=0.50

# Number of windows in master area
default_nmaster=1

# Smart gaps (disable gaps when single window)
smartgaps=0

# Disable centering when single window
center_when_single_stack=0

# Keep master centered with a single client or spread over the screen
center_master_overspread=1 

# Bindings
# Dynamically grow or shrink the master layout split
# bind = ALT,Right,setmfact,+0.25
# bind = ALT,Left,setmfact,-0.25