# Wiki: https://wiki.hypr.land/Configuring/Variables/#animations
animations {
    enabled = true

    # Default curves: https://wiki.hypr.land/Configuring/Animations/#curves
    # NAME                     X0     Y0     X1     Y1

    bezier = decel,            0.05,  0.90,  0.10,  1.00
    bezier = smoothOut,        0.16,  1.00,  0.30,  1.00
    bezier = wsSmooth,         0.22,  1.00,  0.36,  1.00
    bezier = linear,           0.00,  0.00,  1.00,  1.00


    # Default animations: https://wiki.hypr.land/Configuring/Animations/
    # NAME                         ON/OFF SPEED  CURVE            STYLE
    # Windows
    animation = windows,           1,     6,     wsSmooth,        slide
    animation = windowsIn,         1,     6,     wsSmooth,        slide
    animation = windowsOut,        1,     5,     wsSmooth,        slide
    animation = fade,              1,     5,     smoothOut
    animation = border,            1,     8,     smoothOut
    animation = borderangle,       1,     30,    linear,          loop

    # Workspaces
    animation = workspaces,        1,     7,     wsSmooth,        slide
    animation = specialWorkspace,  1,     7,     wsSmooth,        slidevert

    # Layers
    animation = layers,            1,     6,     decel
    animation = layersIn,          1,     6,     decel,           slide
    animation = layersOut,         1,     5,     smoothOut,       slide
}