# See https://wiki.hypr.land/Configuring/Monitors/
# Format: monitor=[name],[resolution],[position],[scale]

## USB-C Port Screen
monitor = DP-2, highres, auto-up, 1

## Laptop screen
monitor = eDP-1, highres, auto, 1

## All other ports
monitor = , highres, auto, 1
